### ISSUE TITLE
my binder link from Jupyter

### ISSUE THREAD

**Issue by smrgeoinfo** [sanil72900/ec21_binder_anil#1]
https://earthcube2021.github.io/ec21_book/notebooks/ec21_anil_etal/README.html my binder link isn't working for me. 
Running Chrome, Windows 10.  MyBinder starts, seems to build image, start server but then I get a 404. 
Address bar in Chrome shows https://hub.gke2.mybinder.org/user/sanil72900-ec21_binder_anil-l7m07xcl/doc/tree/SA_01_Argo_Data_Exploration.ipynb.   

the my binder link from 'copy binder link' button is:
https://mybinder.org/v2/gh/sanil72900/ec21_binder_anil/d7dee0ebccefca909fc97f85dc0b87a001ae5b0b

**Comment by sanil72900** [comment]
Hi, thank you for bringing this to my attention. I've updated all of the binder links so they should be working now. If not, please let me know :)

**Comment by smrgeoinfo** [comment]
I'm still seeing the 404.  When I click the binder link, binder opens "Starting repository: sanil72900/ec21_binder_anil.git/HEAD", says 'Found built image, launching...  Launching server...' . After a few seconds a longer message pops up, too fast to read, and I get the 404 Not found from https://hub.gke2.mybinder.org/.

**Comment by sanil72900** [comment]
Hmm interesting... I checked the links and everything worked on my end. Let me check if this is an issue for other users. If you were able to create binder buttons that work, I'd appreciate it if you could send them to me so I can compare them to mine.
